# Generated by Django 5.0.1 on 2024-03-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CDAlunos', '0002_rename_cadastro_cadastroaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroaluno',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
